import Head from 'next/head';
import styled from 'styled-components';

const Root = styled.div`
  min-height: 100vh;
  padding: 0% 20%;
  display: flex;
  flex-direction: column;
  justify-content: center;

  video {
    position: absolute;
  }
`;

const TextContainer = styled.div`
  z-index: 2;
 
  h1, h2 {
    text-align: center;
  }

  h1 {
    font-size: 1.5rem;
  }

  h2 {
    font-size: 3rem;
  }

  padding-bottom: 10rem;

`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Root>
        <TextContainer>
          <h1>iPhone 13 Pro</h1>
          <h2>Oh. So. Pro.</h2>
        </TextContainer>
        <video 
          autoPlay 
          muted 
          //height={900}
          //width={1000}
          src='/assets/videos/intro-animation.mov'
        />
      </Root>
    </>
  )
}